### ISSUE TITLE
Modules aren't installed during install from pypi with pip.

### ISSUE THREAD

**Issue by eisensheng** [Jokymon/binstruct#1] opened 2015-01-29 15:14 UTC
The install process with 

```
$ pip install binstruct
```

won't install the python modules provided by this project.  The `installed-files.txt` contains only

```
./
PKG-INFO
top_level.txt
SOURCES.txt
dependency_links.txt
```

**Comment by Jokymon** [comment] 2015-03-02 19:06
The issue is fixed with release 1.0.1, commit e22be8e. The packages for Python 2.7 and 3.4 are available on PyPi: https://pypi.python.org/pypi/binstruct/1.0.1.

**Closed as completed by Jokymon** 2015-03-02 19:06 UTC
